config/routes.rb
Rails.application.routes.draw do

  # custom devise_turbo setup
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  #   # get "/topics/:topic_id/offers/new", to: "offers#new", as: :new_offer
  #   get "topics/:topic_id/categories/:category_id/offers", to: "offers#index", as: :offer_index

  # end
  devise_for :users
  scope "/admin" do
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'pages#home'
  # USER DASHBOARD
  get "/profil", to: "dashboards#show"
  get "/admin", to: "dashboards#admin", as: :admin
  get "/blog_board", to: "dashboards#blog_board"
  get "/user_board", to: "dashboards#user_board"
  get "/offer_board", to: "dashboards#offer_board"
  get "/about", to: "pages#about"
  get "/search", to: "searches#index"


  # NESTED ROUTES FOR TOPIC->CATEGORY->OFFERS->OFFER
  resources :topics, only: [:show, :index] do
    resources :categories, only: [:show, :index]
  end


  # UNNESTED OFFERS ROUTES
  resources :offers, only: [:new, :create, :show, :create, :edit, :update, :destroy, :index]
  # UNNESTED CATEGORIES ROUTES
  resources :categories, only: [:new, :create]

  # For changing the offer status
  resources :offers do
    member do
      get :toggle_status
    end
  end

  # Article routes

  resources :articles, except: :destroy do
    member do
      get :toggle_status
    end
  end
  delete '/articles/:id', to: 'articles#destroy', as: :delete_article


  #sidekiq

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :content, :title, presence: true
  enum :status, { inactive: 0, active: 1, archived: 2 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :toggle_status]
  after_action :send_article_email, only: [:create]


  def show
    @user = User.find(@article.user_id)
    @offers = Offer.find(@user.offer_ids.sample(3))
  end

  def index
    @articles = Article.where(status: 1).all.order("created_at DESC")
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @article.user = current_user
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    if @article.delete
      redirect_to blog_board_path, status: :see_other
    end
  end

  def toggle_status

    if @article.active?
      @article.inactive!
    else
      @article.active!
    end
    redirect_to blog_board_url, notice: 'Post status has been updated.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :user_id, :photo)
  end
  def send_article_email
    AdminMailer.with(user: @user).article.deliver_now
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="adminOffer">
<h1>Blog Posts</h1>
<%= link_to "Neuer Post", new_article_path, class: "btn btn-dark" %>
<div class="cardList">
    <div class="cardOffer header one">
      <h4  class="cardTitle header">
        Titel
      </h4>
      <h4 class="header">
        Anbieter
      </h4>
      <h4 class="header">
        Datum
      </h4>
      <div class="buttons header" style="gap:1rem">
        <h4>
          Bearbeiten
        </h4>
        <h4>
          Löschen
        </h4>
      </div>
    </div>
    <% @articles.each do |article| %>
    <div class="cardOffer">
    <strong  class="cardTitle">
      <%= link_to article.title, article_path(article), class: "cardTitle" %>
    </strong>
    <div class="">
      <%= article.user.email %>
    </div>
    <div class="">
     <%= article.created_at.to_date.strftime("%d-%m-%Y") %>
    </div>
    <div class="buttons">
      <% if user_signed_in? && (current_user.role == "admin" || current_user.role == "institution") %>
      <%= link_to "Bearbeiten", edit_article_path(article) %>
      <%= link_to "Löschen", delete_article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
        <% end %>
    </div>
  </div>
  <% end %>
</div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <%= simple_form_for @article do |f| %>
    <%= f.input :title %>
    <%= f.input :content, as: :text, class: "article-text" %>
    <div data-controller="preview">
      <%= f.label "Add a Picture" %>
      <%= f.input :photo, as: :file, input_html: { id:'inpFile'}, data: { action:"change->preview#connect"} %>
       <div class="image-preview" id="image-preview">
          <img src="" alt="image preview" class="image-preview__image">
       <span class="image-preview__default-text">Image Preview</span>
        </div>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="site">
  <div class="topics-info-text ">
    <h3 class="sprechblase_unten">Hier gibt es die aktuellsten Nachrichten <br> über die Angebote aus deiner Umbegbung </h3>
  </div>
  <div class="article">
    <% @articles.each do |article| %>
      <%= link_to article_path(article), class: "text" do%>
        <div class="article_card <%= article.id % 2 == 0 ? '' : 'article_card_left' %>">
          <% if article.photo.attached? %>
            <div class="article_photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path article.photo.key %>')">
            </div>
            <% else %>
            <div class="article_photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
          <% end %>
          <div class="article_card_text">
            <h3><%= article.title %></h3>
            <p>von <%= User.find(article.user_id).email %> | <%= article.created_at.to_date.strftime("%d-%m-%Y")%> </p>
            <p><%= article.content.truncate(50)%></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="adminOffer">
    <h1>Schreibe einen neuen Post</h1>
    <%= simple_form_for @article do |f| %>
      <%= f.input :title, class: "article-new-title" %>
      <%= f.input :content, as: :text, class: "article-new-text" %>
      <div data-controller="preview">
        <%= f.label "Bild hinzufügen" %>
        <%= f.input :photo, as: :file, input_html: { id:'inpFile'}, data: { action:"change->preview#connect"} %>
        <div class="image-preview" id="image-preview">
          <img src="" alt="image preview" class="image-preview__image">
          <span class="image-preview__default-text">Vorschau</span>
        </div>
      </div>
      <%= f.submit value: "Fertig" , class:"btn-info btn_form"%>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="offer">
  <% if @article.photo.attached? %>
    <div class="image" style="background-image: url('<%= cl_image_path @article.photo.key %>')"></div>
  <% else %>
    <div class="image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
  <% end %>
  <div class="title box">
    <h1>
      <%= @article.title %>
    </h1>
    <div class="flex">
      <p>Ein Beitrag von <%= @article.user.email %></p>
      <div>
        <% if user_signed_in? && (current_user.role == "admin" || current_user.role == "institution") %>
          <%= link_to "Destroy", article_path(@article), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            },
            class:"btn btn-info" %>
          <%= link_to "Edit", edit_article_path(@article), data: {
            turbo_method: :edit
            },
            class:"btn btn-info" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="description box">
    <%=  @article.content %>
  </div>
    <h2>Angbote des Autors</h2>
    <div class="liste">
      <% @offers.each do |offer| %>
      <%= link_to offer_path(offer), class: "text" do%>
          <div class="post_card_two" style="width: 100%;">
            <% if offer.photo.attached? %>
              <div class="post_photo_two" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path offer.photo.key %>')">
              </div>
              <% else %>
              <div class="post_photo_two" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
            <% end %>
            <div class="post_card_text">
              <h3><%= offer.title %></h3>
              <p>von <%= User.find(offer.user_id).email %> | <%= offer.created_at.to_date.strftime("%d-%m-%Y")%> </p>
              <h6><%= offer.description.truncate(50)%></h6>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>