config/routes.rb
Rails.application.routes.draw do

  # custom devise_turbo setup
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  #   # get "/topics/:topic_id/offers/new", to: "offers#new", as: :new_offer
  #   get "topics/:topic_id/categories/:category_id/offers", to: "offers#index", as: :offer_index

  # end
  devise_for :users
  scope "/admin" do
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'pages#home'
  # USER DASHBOARD
  get "/profil", to: "dashboards#show"
  get "/admin", to: "dashboards#admin", as: :admin
  get "/blog_board", to: "dashboards#blog_board"
  get "/user_board", to: "dashboards#user_board"
  get "/offer_board", to: "dashboards#offer_board"
  get "/about", to: "pages#about"
  get "/search", to: "searches#index"


  # NESTED ROUTES FOR TOPIC->CATEGORY->OFFERS->OFFER
  resources :topics, only: [:show, :index] do
    resources :categories, only: [:show, :index]
  end


  # UNNESTED OFFERS ROUTES
  resources :offers, only: [:new, :create, :show, :create, :edit, :update, :destroy, :index]
  # UNNESTED CATEGORIES ROUTES
  resources :categories, only: [:new, :create]

  # For changing the offer status
  resources :offers do
    member do
      get :toggle_status
    end
  end

  # Article routes

  resources :articles, except: :destroy do
    member do
      get :toggle_status
    end
  end
  delete '/articles/:id', to: 'articles#destroy', as: :delete_article


  #sidekiq

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  geocoded_by :postcode_german
  after_validation :geocode, if: :will_save_change_to_postcode?
  enum status: { inactive: 0, active: 1, cancelled: 2 }
  belongs_to :user
  has_many :category_offers, dependent: :destroy
  has_many :categories, :through => :category_offers

  # Cloudinary
  has_one_attached :photo

  # Validations
  validates :title, :description, :about_us, :email, :postcode, :category_ids, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [ :title ],
    using: {
      tsearch: { prefix: true }
    }

  # Get full address
  def full_address
    [address, town, postcode].compact.join(", ")
  end

  # Get correct Postcode for geocoder
  def postcode_german
    "#{postcode}, Deutschland"
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # before_action :set_offers_index, only: :index
  before_action :set_offer, only: [:show, :edit, :destroy, :toggle_status]

  def index
    @category = Category.find(params[:topic_id])
    @offers = @category.offers
  end

  def show
    @user = User.find(@offer.user_id)
    @articles = Article.find(@user.article_ids.sample(3))
  end

  def new
    @offer = Offer.new
    @user = current_user
    # @topic = Topic.find(params[:topic_id])
    # @categories = @topic.categories
    # @offer.category_offers.build
    authorize @offer
  end

  def create
    @user = current_user
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id
    # @offer.category_offers.build

    if @offer.save
      # UserMailer.with(user: @user).welcome.deliver_now
      EmailJob.set(wait: 1.minute).perform_later(@user.id, @offer.id)
      redirect_to offer_board_path

    else
      render "new"
    end
    authorize @offer
  end

  def edit
    authorize Offer
    @offer = Offer.find(params[:id])
    @user = current_user
    @offer.category_offers.build
    authorize @offer
  end

  def update
    authorize Offer
    @offer = Offer.find(params[:id])
    if @offer.update(offer_params)

      redirect_to @offer
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @offer.destroy
      if current_user.role == "admin"
        redirect_to offer_board_path, status: :see_other
      else
      redirect_to profil_path, status: :see_other
      end
    end
  end

  def toggle_status
    if @offer.active?
      @offer.inactive!
    else
      @offer.active!


    end
    redirect_to offer_board_url, notice: 'Post status has been updated.'
  end

  private

  def set_offers_index
    @offers = Offer.find(params[:category_id])
  end

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:user_id, :title, :description, :phone, :url, :about_us, :town, :email, :address, :postcode, :photo, category_ids: [])
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/edit.html.erb
<div class="container mx-auto mt-5">
  <h1 class="text-center ">Angebot bearbeiten</h1>
  <div class="offer_form mt-5">
  <%= simple_form_for @offer do |f| %>
    <%= f.input :title, placeholder: 'title' %>
    <%= f.input :description, placeholder: 'description' %>
    <%= f.input :about_us, placeholder: 'about_us' %>
    <%= f.input :email, placeholder: 'email' %>
    <%= f.input :address, placeholder: 'address' %>
    <%= f.input :town, placeholder: 'ort' %>
    <%= f.input :postcode, placeholder: 'postcode' %>
    <div data-controller="preview">
      <%= f.label "Add a Picture" %>
      <%= f.input :photo, as: :file, input_html: { id:'inpFile'}, data: { action:"change->preview#connect"} %>
      <div class="image-preview" id="image-preview">
        <img src="" alt="image preview" class="image-preview__image">
        <span class="image-preview__default-text">Image Preview</span>
      </div>
    </div>
    <%= f.submit class: "btn btn-dark" %>
  <% end %>
  </div>
</div>
<%= link_to "back",  offer_path(@offer) %>

app/views/offers/edit.js.erb
  const inpFile = document.getElementById('inpFile');
  const previewContainer = document.getElementById('imagePreview');
  const previewImage = previewContainer.querySelector('.image-preview__image');
  const previewDefaultText = previewContainer.querySelector('.image-preview__default-text');

  inpFile.addEventListener("change",function() {
    const file = this.files[0]
    console.log(file)
  })

app/views/offers/index.html.erb
<h1>Offers#index</h1>
<p>Find me in app/views/offers/index.html.erb</p>
<% @offers.each do |offer| %>
  <%= link_to offer.title, offer_path(offer) %>
<% end %>

app/views/offers/new.html.erb
<div class="container">
  <div class="offer_form">
  <%= simple_form_for @offer do |f| %>

    <%= f.input :title, placeholder: 'z.B. "Fußball AG"',label: "Titel des Angebots" %>
    <%= f.input :description, placeholder: '  ...', label: "Beschreiben Sie das Angebot in einigen Sätzen." %>
    <%= f.input :about_us, placeholder: '  ...', label: "Geben Sie Infos über Ihre Organisation." %>
    <%= f.input :email, placeholder: 'max@mustermann.de', label: "Unter welcher Mailadresse möchten Sie erreichbar sein?" %>
    <%= f.input :phone, placeholder: '+49 ...', label: "Unter welcher Telefonnummer möchten Sie erreichbar sein?" %>
    <%= f.input :address, placeholder: 'z.B. "Seidenstraße 13"', label: "Möchten Sie eine Adresse anzeigen?" %>
    <%= f.input :town, placeholder: 'Wusterhausen', label: "In welchem Ort ist das Angebot?" %>
    <%= f.input :postcode, placeholder: 'postcode', label: "Bitte hinterlegen Sie eine Postleitzahl" %>
    <br>
    <div class="categories-choice-div" data-controller="category-button">
      <h4>Bitte wählen Sie ein Thema aus</h4>
      <br>
      <div class="category-choice-buttons-container">
        <button class="btn btn-danger choose-cat-btn"
          data-action="click->category-button#enableone"
          data-category-button-target="choicebuttonone"
          href=""
          >Schule
        </button>
        <button class="btn btn-info choose-cat-btn"
          data-action="click->category-button#enabletwo"
          data-category-button-target="choicebuttontwo"
          href=""
          >Freizeit
        </button>
        <button class="btn btn-success choose-cat-btn"
          data-action="click->category-button#enablethree"
          data-category-button-target="choicebuttonthree"
          href=""
          >Ausbildung
        </button>
        <button class="btn btn-dark choose-cat-btn"
          data-action="click->category-button#enablefour"
          data-category-button-target="choicebuttonfour"
          href=""
          >Jugenhilfe
        </button>
      </div>
      <div class="result" data-category-button-target="choicecontainer">
      </div>
      <div class="category-choice-container">
        <div class="disable">
          <div class="categories-choice-one categories-choice-container" data-category-button-target="one">
            <br>
            <%= f.label "Wählen Sie eine oder mehrere Kategorien" %>
            <div class="d-flex">
              <%= f.association :categories, collection: Category.topic_one, as: :check_boxes, label: "Wählen Sie eine oder mehrere Kategorien", input_html: { class: "categories-choice-field" } %>
            </div>
          </div>
          <br>
          <div class="categories-choice-two categories-choice-container" data-category-button-target="two">
            <br>
            <%= f.label "Wähle eine oder mehrere Kategorien" %>
            <div class="d-flex">
              <%= f.association :categories, collection: Category.topic_two, as: :check_boxes, label: "Wählen Sie eine oder mehrere Kategorien", input_html: { class: "categories-choice-field" } %>
            </div>
          </div>
          <br>
          <div class="categories-choice-three categories-choice-container" data-category-button-target="three">
            <br>
            <%= f.label "Wähle eine oder mehrere Kategorien" %>
            <div class="d-flex">
              <%= f.association :categories, collection: Category.topic_three, as: :check_boxes, label: "Wählen Sie eine oder mehrere Kategorien", input_html: { class: "categories-choice-field" } %>
            </div>
          </div>
          <br>
          <div class="categories-choice-four categories-choice-container" data-category-button-target="four">
            <br>
            <%= f.label "Wähle eine oder mehrere Kategorien" %>
            <div class="d-flex">
              <%= f.association :categories, collection: Category.topic_four, as: :check_boxes, label: "Wählen Sie eine oder mehrere Kategorien", input_html: { class: "categories-choice-field" } %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= f.label "Anzeigephoto hochladen?", class: "upload-label" %>
    <%= f.input :photo, as: :file, label: false %>
    <br>
    <%= f.submit "Angebot erstellen", class: "btn btn-dark" %>
    <div class="bearbeitungszeit">
      <p><em>*(Bis Sie das Angebot auf unserer Seite sehen können, muss es von einem Moderator freigegeben werden.</em></p>
      <p><em>Wir bitten daher um ein wenig Geduld, wir beeilen uns Ihr Angebot zu bearbeiten!)</em></p>
    </div>
  <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="offer">
  <% if @offer.photo.attached? %>
    <div class="image" style="background-image: url('<%= cl_image_path @offer.photo.key %>')"></div>
  <% else %>
    <div class="image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
  <% end %>
  <div class="title box">
    <h1>
      <%= @offer.title %>
    </h1>
  <div class="flex">
      <div class="categories">
        <% @offer.categories.each do |category|%>
          <p><%= category.title %></p>
        <% end %>
      </div>
      <div>
        <% if user_signed_in? && (current_user.role == "admin" || current_user.role == "institution") %>
          <%= link_to "Destroy", offer_path(@offer), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            },
            class:"btn btn-info" %>
          <%= link_to "Edit", edit_offer_path(@offer), data: {
            turbo_method: :edit
            },
            class:"btn btn-info" %>
        <% end %>
      </div>
    </div>
    <%= @offer.url %>
  </div>
  <div class="description box">
    <%= @offer.description %>
  </div>
  <div class="about_us box">
    <h5>Über uns</h5>
    <%= @offer.about_us %>
  </div>
  <div class="box">
    <h5>Kontakt</h5>
    <div class="address">
      <div>
        <h6>Anschrift</h6>
        <%= @offer.address %>
        <%= @offer.postcode %>
      </div>
      <div>
        <h6>Email</h6>
        <%= @offer.email %>
      </div>
      <div>
        <h6>Telefon</h6>
        <%= @offer.phone %>
      </div>
    </div>
  </div>
  <div class="links">
    <h2>News des Anbieters</h2>
    <div class="liste">
      <% @articles.each do |article| %>
      <%= link_to article_path(article), class: "text" do%>
          <div class="post_card_two" style="width: 100%;">
            <% if article.photo.attached? %>
              <div class="post_photo_two" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path article.photo.key %>')">
              </div>
              <% else %>
              <div class="post_photo_two" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')"></div>
            <% end %>
            <div class="post_card_text">
              <h3><%= article.title %></h3>
              <p>von <%= User.find(article.user_id).email %> | <%= article.created_at.to_date.strftime("%d-%m-%Y")%> </p>
              <h6><%= article.content.truncate(50)%></h6>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>