config/routes.rb
Rails.application.routes.draw do

  # custom devise_turbo setup
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  #   # get "/topics/:topic_id/offers/new", to: "offers#new", as: :new_offer
  #   get "topics/:topic_id/categories/:category_id/offers", to: "offers#index", as: :offer_index

  # end
  devise_for :users
  scope "/admin" do
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'pages#home'
  # USER DASHBOARD
  get "/profil", to: "dashboards#show"
  get "/admin", to: "dashboards#admin", as: :admin
  get "/blog_board", to: "dashboards#blog_board"
  get "/user_board", to: "dashboards#user_board"
  get "/offer_board", to: "dashboards#offer_board"
  get "/about", to: "pages#about"
  get "/search", to: "searches#index"


  # NESTED ROUTES FOR TOPIC->CATEGORY->OFFERS->OFFER
  resources :topics, only: [:show, :index] do
    resources :categories, only: [:show, :index]
  end


  # UNNESTED OFFERS ROUTES
  resources :offers, only: [:new, :create, :show, :create, :edit, :update, :destroy, :index]
  # UNNESTED CATEGORIES ROUTES
  resources :categories, only: [:new, :create]

  # For changing the offer status
  resources :offers do
    member do
      get :toggle_status
    end
  end

  # Article routes

  resources :articles, except: :destroy do
    member do
      get :toggle_status
    end
  end
  delete '/articles/:id', to: 'articles#destroy', as: :delete_article


  #sidekiq

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @offers = current_user.offers
  end

  def admin
    if params[:query].present?
      if /\b((?:0[1-46-9]\d{3})|(?:[1-357-9]\d{4})|(?:[4][0-24-9]\d{3})|(?:[6][013-9]\d{3}))\b/.match(params[:query])
        @offers = Offer.where(postcode: "#{params[:query]}")
      else
        # IF NOT ZIPCODE LOOKS FOR OFFER TITLE
        @offers = Offer.search_by_title("%#{params[:query]}%")
      end
      # sql_query = " \
      #   offers.title @@ :query \
      #   OR offers.postcode @@ :query \
      # "
    else
      @offers = Offer.all.order('created_at DESC')
    end
  end

  def blog_board
    if params[:query].present?
      # Search by title
      @articles = Article.search_by_title("%#{params[:query]}%")
    else
      @articles = Article.all.order("created_at DESC")
    end
  end

  def user_board
    if params[:query].present?
      # Search by title
      @users = User.search_by_email("%#{params[:query]}%")
    else
      @users = User.all
    end
  end

  def destroy
    @user = Users.find(params[:id])
    @user.destroy!

    redirect_to user_board_path

    respond_to do |format|
      format.xml  { head :ok }
      format.json { respond_to_destroy(:ajax) }
      format.html { respond_to_destroy(:html) }
    end
  end

  def offer_board
    if params[:query].present?
      if /\b((?:0[1-46-9]\d{3})|(?:[1-357-9]\d{4})|(?:[4][0-24-9]\d{3})|(?:[6][013-9]\d{3}))\b/.match(params[:query])
        @offers = Offer.where(postcode: "#{params[:query]}")
      else
        # IF NOT ZIPCODE LOOKS FOR OFFER TITLE
        @offers = Offer.search_by_title("%#{params[:query]}%")
      end
      # sql_query = " \
      #   offers.title @@ :query \
      #   OR offers.postcode @@ :query \
      # "
    else
      @offers = Offer.all.order('created_at DESC')
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_activeArticles.html.erb
<div class="adminOffer">
  <div class="admin-search-bar">
    <h1>Aktive Posts</h1>
  </div>
  <div class="cardList">
      <div class="cardOffer header one">
        <div class="cardText">
          <h4  class="cardTitle header">
            Titel
          </h4>
          <h4 class="header">
            Anbieter
          </h4>
          <h4 class="header">
            Datum
          </h4>
        </div>
        <div class="buttons header" style="gap:1rem">
          <h4>
            Deaktivieren
          </h4>
          <h4>
            Löschen
          </h4>
        </div>
      </div>
      <% @articles.where(status: "active").each do |article| %>
      <div class="cardOffer">
        <div class="cardText">
          <strong  class="cardTitle">
            <%= link_to article.title, article_path(article), class: "cardTitle", data: { turbo: false }  %>
          </strong>
          <div class="email">
            <%= article.user.email %>
          </div>
          <div class="date">
            <%= article.created_at.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="buttons">
          <%= link_to "Deaktivieren", toggle_status_article_path(article), class: "btn btn-info" %>
          <%= link_to "Löschen", article_path(article),class: "btn btn-info", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/_activeOffers.html.erb
<div class="adminOffer">
  <div class="admin-search-bar">
    <h1>Aktive Angebote</h1>

  </div>
  <div class="cardList">
      <div class="cardOffer header one">
        <div class="cardText">
          <h4  class="cardTitle header">
            Titel
          </h4>
          <h4 class="header">
            Anbieter
          </h4>
          <h4 class="header">
            Datum
          </h4>
        </div>
        <div class="buttons header" style="gap:1rem">
          <h4>
            Deaktivieren
          </h4>
          <h4>
            Löschen
          </h4>
        </div>
      </div>
      <% @offers.where(status: "active").each do |offer| %>
      <div class="cardOffer">
        <div class="cardText">
          <strong  class="cardTitle">
            <%= link_to offer.title, offer_path(offer), class: "cardTitle", data: { turbo: false }  %>
          </strong>
          <div class="email">
            <%= offer.user.email %>
          </div>
          <div class="date">
            <%= offer.created_at.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="buttons">
          <%= link_to "Deaktivieren", toggle_status_offer_path(offer), class: "btn btn-info" %>
          <%= link_to "Löschen", offer_path(offer),class: "btn btn-info", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/_inactiveArticles.html.erb
<div class="adminOffer">
  <h1>Inaktive Posts</h1>
  <div class="cardList">
      <div class="cardOffer header one">
        <div class="cardText">
          <h4  class="cardTitle header">
            Titel
          </h4>
          <h4 class="header">
            Anbieter
          </h4>
          <h4 class="header">
            Datum
          </h4>
        </div>
        <div class="buttons header">
          <h4>
            Aktivieren
          </h4>
          <h4>
            Löschen
          </h4>
        </div>
      </div>
      <% @articles.where(status: "inactive").each do |article| %>
      <div class="cardOffer">
        <div class="cardText">
          <strong  class="cardTitle">
            <%= link_to article.title, article_path(article), class: "cardTitle", data: { turbo: false } %>
          </strong>
          <div class="">
            <%= article.user.email %>
          </div>
          <div class="">
          <%= article.created_at.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="buttons">
          <%= link_to "Aktivieren", toggle_status_article_path(article), class: "btn btn-info" %>
          <%= link_to "Löschen", article_path(article),class: "btn btn-info", data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
            } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/_inactiveOffers.html.erb
<div class="adminOffer">
  <h1>Inaktive Angebote</h1>
  <div class="cardList">
      <div class="cardOffer header one">
        <div class="cardText">
          <h4  class="cardTitle header">
            Titel
          </h4>
          <h4 class="header">
            Anbieter
          </h4>
          <h4 class="header">
            Datum
          </h4>
        </div>
        <div class="buttons header">
          <h4>
            Aktivieren
          </h4>
          <h4>
            Löschen
          </h4>
        </div>
      </div>
      <% @offers.where(status: "inactive").each do |offer| %>
      <div class="cardOffer">
        <div class="cardText">
          <strong  class="cardTitle">
            <%= link_to offer.title, offer_path(offer), class: "cardTitle" %>
          </strong>
          <div class="">
            <%= offer.user.email %>
          </div>
          <div class="">
          <%= offer.created_at.to_date.strftime("%d-%m-%Y") %>
          </div>
        </div>
        <div class="buttons">
          <%= link_to "Aktivieren", toggle_status_offer_path(offer), class: "btn btn-info" %>
          <%= link_to "Löschen", offer_path(offer),class: "btn btn-info", data: {
            turbo_method: :delete,
                          turbo_confirm: "Are you sure?"
                        } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/admin.html.erb
<%= turbo_frame_tag "admin" do %>
  <div class="nav_admin">
    <%= link_to "Angebote", offer_board_path, class:"button_admin"%>
    <%= link_to "News", blog_board_path, class:"button_admin" %>
    <%= link_to "User", user_board_path, class:"button_admin" %>
  </div>
<%end%>

app/views/dashboards/blog_board.html.erb
<%= turbo_frame_tag "admin" do %>
  <div class="nav_admin">
    <%= link_to "Angebote", offer_board_path, class:"button_admin offer"%>
    <%= link_to "News", blog_board_path, class:"button_admin blog on" %>
    <%= link_to "User", user_board_path, class:"button_admin user" %>
    <div class="new_o"></div>
    <%= link_to "Neuer Post", new_article_path, class: "button_admin new_u", data: { turbo: false } %>
    <div class="new_u"></div>
  </div>
  <div class="container">
    <%= render "activeArticles" %>
    <%= render "inactiveArticles" %>
  </div>
<% end %>

app/views/dashboards/offer_board.html.erb
<%= turbo_frame_tag "admin" do %>

  <div class="nav_admin">
    <%= link_to "Angebote", offer_board_path, class:"button_admin offer on"%>
    <%= link_to "News", blog_board_path, class:"button_admin blog" %>
    <%= link_to "User", user_board_path, class:"button_admin user" %>
    <%= link_to "Neues Angebot", new_offer_path, class: "button_admin new_o", data: { turbo: false } %>
    <div class="new_b"></div>
    <div class="new_u"></div>
    <%= link_to "Neue Kategorie", new_category_path, class: "button_admin new_c", data: { turbo: false } %>

  </div>
<div class="container">
  <div class="admin-container">
      <% if current_user.role == "admin" %>
        <div class="search-container d-flex justify-content-center">

          <%= form_tag admin_path, method: :get do %>
            <div class="d-flex">
              <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Stichwort oder PLZ"
              %>
              <%= submit_tag "Search", class: "btn btn-dark", id: "search-button" %>
            <%# <button type="submit" form="search" value="Submit" class="shiny_black">Submit</button> %>
            </div>
          <% end %>
        </div>



          <%= render "activeOffers" %>
          <%= render "inactiveOffers" %>

        <!-- Buttons
        <div class="new-category-link d-flex justify-flex-start">
          <%= link_to "Neues Angebot", new_offer_path, class: "shiny_green", data: {turbo: false} %>
          <%= link_to "Neue Kategorie", new_category_path, class: "shiny_yellow" , data: {turbo: false}%>
        </div>
        -->
      <% else %>
        <h1 style="text-align: center; margin-top: 50px;">This area is not for you...</h1>
      <% end %>
    </div>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<div class="container">
  <% if current_user.role == "institution" || current_user.role == "admin" %>
    <div class="admin">
      <%= render "activeOffers" %>
      <%= render "inactiveOffers" %>
    </div>
      <div class="new-category-link d-flex justify-flex-start">

        <%= link_to "Neues Angebot", choose_topic_path, class: "shiny_green" %>
      </div>
  <% else %>
    <h1 style="text-align: center; margin-top: 50px;">This area is not for you...</h1>
  <% end %>
</div>

app/views/dashboards/user_board.html.erb
<%= turbo_frame_tag "admin" do %>
<div class="nav_admin">
  <%= link_to "Angebote", offer_board_path, class:"button_admin offer"%>
  <%= link_to "News", blog_board_path, class:"button_admin blog" %>
  <%= link_to "User", user_board_path, class:"button_admin user on" %>
  <div class="new_o"></div>
  <div class="new_b"></div>
  <%= link_to "Neuen User", new_user_path, class: "button_admin new_u", data: { turbo: false } %>

</div>
  <div class="container">
  <div class="admin-container">
    <h1>User</h1>
      <div class="cardListArticles">
          <div class="cardOffer header one">
            <div class="cardText">
              <h4  class="cardTitle header">
                Name
              </h4>
              <h4 class="header">
                Email
              </h4>
              <h4 class="header">
                Datum
              </h4>
            </div>
            <% if current_user %>
              <% if current_user.role == "institution" || current_user.role == "admin" %>
              <div class="buttons header">
                <h4>
                  Löschen
                </h4>
              </div>
              <% end %>
            <% end %>
          </div>
          <% @users.each do |user| %>
          <div class="cardOffer">
          <div class="cardText">
          <strong  class="cardTitle">
            <%= user.name %>
          </strong>
          <div class="email">
            <%= user.email %>
          </div>
          <div class="date">
          <%= user.created_at.to_date.strftime("%d-%m-%Y") %>
          </div>
          </div>
          <% if current_user %>
            <% if current_user.role == "institution" || current_user.role == "admin" %>
              <div class="buttons">
                 <%= button_to "Delete", user_path(user),class: "btn btn-info", method: :delete %>
              </div>
            <% end %>
          <% end %>
        </div>
        <% end %>
      </div>
      <!-- BUTTON
      <% if current_user %>
        <% if current_user.role == "institution" || current_user.role == "admin" %>
          <div class="new-article-link d-flex justify-flex-start">
            <%= link_to "Neuen User", new_user_path, class: "shiny_green", data: { turbo: false } %>
          </div>
        <% end %>
      <% end %>
      -->
    </div>
  </div>
<% end %>