config/routes.rb
Rails.application.routes.draw do

  # custom devise_turbo setup
  # devise_scope :user do
  #   # Redirests signing out users back to sign-in
  #   get "users", to: "devise/sessions#new"
  #   # get "/topics/:topic_id/offers/new", to: "offers#new", as: :new_offer
  #   get "topics/:topic_id/categories/:category_id/offers", to: "offers#index", as: :offer_index

  # end
  devise_for :users
  scope "/admin" do
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: 'pages#home'
  # USER DASHBOARD
  get "/profil", to: "dashboards#show"
  get "/admin", to: "dashboards#admin", as: :admin
  get "/blog_board", to: "dashboards#blog_board"
  get "/user_board", to: "dashboards#user_board"
  get "/offer_board", to: "dashboards#offer_board"
  get "/about", to: "pages#about"
  get "/search", to: "searches#index"


  # NESTED ROUTES FOR TOPIC->CATEGORY->OFFERS->OFFER
  resources :topics, only: [:show, :index] do
    resources :categories, only: [:show, :index]
  end


  # UNNESTED OFFERS ROUTES
  resources :offers, only: [:new, :create, :show, :create, :edit, :update, :destroy, :index]
  # UNNESTED CATEGORIES ROUTES
  resources :categories, only: [:new, :create]

  # For changing the offer status
  resources :offers do
    member do
      get :toggle_status
    end
  end

  # Article routes

  resources :articles, except: :destroy do
    member do
      get :toggle_status
    end
  end
  delete '/articles/:id', to: 'articles#destroy', as: :delete_article


  #sidekiq

  require 'sidekiq/web'
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :topic
  has_many :category_offers, dependent: :destroy
  has_many :offers, :through => :category_offers
  validates :title, presence: true
  has_one_attached :photo

  # SCOPES
  scope :topic_one, -> { where(topic_id: 1) }
  scope :topic_two, -> { where(topic_id: 2) }
  scope :topic_three, -> { where(topic_id: 3) }
  scope :topic_four, -> { where(topic_id: 4) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: :show

  def index
    @topic = Topic.find(params[:topic_id])
    @categories = @topic.categories
  end

  def show
    @offers = @category.offers.where(status: "active")
    @topic = Topic.find(params[:id])
  end

  def new
    @category = Category.new
    @topics = Topic.all
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    @topic = @category.topic
    authorize @category
    if @category.save
      redirect_to topic_path(@topic)
    else
      render :new
    end
    authorize @category
  end

  private

  def category_params
    params.require(:category).permit(:title, :topic_id, :photo)
  end

  def set_category
    @category = Category.find(params[:topic_id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_offer_card.html.erb
  <div class="blog-card">
    <div class="meta">
      <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg)"></div>
      <ul class="details">
        <li class="author"><a href="#">John Doe</a></li>
        <li class="date">Aug. 24, 2015</li>
        <li class="tags">
          <ul>
            <li><a href="#">Learn</a></li>
            <li><a href="#">Code</a></li>
            <li><a href="#">HTML</a></li>
            <li><a href="#">CSS</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Learning to Code</h1>
      <h2>Opening a door to the future</h2>
      <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad eum dolorum architecto obcaecati enim dicta praesentium, quam nobis! Neque ad aliquam facilis numquam. Veritatis, sit.</p>
      <p class="read-more">
        <a href="#">Read More</a>
      </p>
    </div>
  </div>
  <div class="blog-card alt">
    <div class="meta">
      <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-2.jpg)"></div>
      <ul class="details">
        <li class="author"><a href="#">Jane Doe</a></li>
        <li class="date">July. 15, 2015</li>
        <li class="tags">
          <ul>
            <li><a href="#">Learn</a></li>
            <li><a href="#">Code</a></li>
            <li><a href="#">JavaScript</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="description">
      <h1>Mastering the Language</h1>
      <h2>Java is not the same as JavaScript</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad eum dolorum architecto obcaecati enim dicta praesentium, quam nobis! Neque ad aliquam facilis numquam. Veritatis, sit.</p>
      <p class="read-more">
        <a href="#">Read More</a>
      </p>
    </div>
  </div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

<% @categories.each do |cat| %>
  <%= link_to cat.title, topic_category_path(cat) %>
<% end %>

app/views/categories/new.html.erb
<div class="container">
  <%= simple_form_for @category do |f| %>
    <%= f.label "Wie soll die Kategorie heißen?" %>
    <%= f.input :title, label: false %>
    <%= f.label "Welchem Thema soll diese Kategorie angehören?" %>
    <%= f.association :topic, collection: @topics, label: false %>
    <%= f.label "Bitte fügen Sie ein Hintergrundbild hinzu." %>
    <%= f.input :photo, as: :file, label: false %>
    <%= f.submit %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="entdecken-header">
  <h3 class="sprechblase_oben">Et voilà! Hier sind unsere Angebote zu Deinen Vorlieben 👇</h3>
</div>
<div class="offer-cards-container">
  <% @offers.each do |offer| %>
    <div class="offer-card-container">
    <% if offer.photo.attached? %>
      <div class="offer-card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path offer.photo.key %>')">
        <div class="offer-card-heading">
          <h4><%= offer.title %></h4>
          <p><%= offer.user.email %> / <%= offer.full_address %></p>
          <%= link_to offer_path(offer) do %>
            <div class="offer-card-button"><h3>C L I C K</h3></div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="offer-card-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1645976417695-e76bf772b1bd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2071&q=80')">
        <div class="offer-card-heading">
          <h4><%= offer.title %></h4>
          <p><%= offer.user.email %> / <%= offer.full_address %></p>
          <%= link_to offer_path(offer) do %>
            <div class="offer-card-button"><h3>C L I C K</h3></div>
          <% end %>
        </div>
      </div>
    <% end %>
      <div class="offer-card-text">
        <p><%= offer.description %></p>
      </div>
    </div>
  <% end %>
</div>

<%# ----> BACK BUTTON <---- %>
<div class="d-flex justify-content-center">
  <%= link_to 'Back', 'javascript:history.back()', class: "shiny_blue", style: "margin-top: 50px;" %>
</div>

<%# PUFFER TO ADD WHITESPACE AT BOTTOM OF PAGE %>
<div class="puffer">
</div>